{{- /*
Frontend Deployment - serves admin web at '/'.
*/ -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "headmail.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "headmail.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.frontend.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "headmail.name" . }}
      component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "headmail.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: frontend
    spec:
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{ if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{ if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{ if .Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: {{ include "headmail.image" (dict "context" . "image" .Values.frontend.image) | quote }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPorts.web | default 80 }}
          env:
            {{- range $k, $v := .Values.frontend.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- if .Values.backend.resources }}
          resources: {{ toYaml .Values.frontend.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: {{ .Values.frontend.livenessProbe.periodSeconds | default 10 }}
          {{- end }}
