// Copyright 2025 JC-Lab
// SPDX-License-Identifier: AGPL-3.0-or-later

package main

import (
	"context"
	"flag"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/headmail/headmail/pkg/config"
	"github.com/headmail/headmail/pkg/server"

	_ "github.com/headmail/headmail/docs" // docs is generated by Swag CLI
)

// @title Headmail API
// @version 1.0
// @description This is an email campaign API server.

// @contact.name API Support
// @contact.url https://headmail.io
// @contact.email dev@headmail.io

// @license.name AGPL-3.0
// @license.url  https://opensource.org/license/agpl-v3

// @BasePath /api
func main() {
	var configPath string
	flag.StringVar(&configPath, "config", "", "Path to the configuration file")
	flag.Parse()

	var opts []config.Option
	if configPath != "" {
		opts = append(opts, config.WithFile(configPath))
	}

	cfg, err := config.Load(opts...)
	if err != nil {
		log.Fatalf("Failed to load configuration: %v", err)
	}

	srv, err := server.New(cfg)
	if err != nil {
		log.Fatalf("Failed to create server: %v", err)
	}

	log.Println("Starting Headmail server...")
	srv.Serve()

	// Wait for interrupt signal to gracefully shut down the servers
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Shutting down servers...")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Fatalf("Server shutdown failed: %v", err)
	}

	log.Println("Servers gracefully stopped")
}
