name: Publish Docker image to GitHub Container Registry

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      TAG: ${{ steps.tag.outputs.TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.25
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Extract tag
        id: tag
        run: |
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binaries for target platforms
        run: |
          mkdir -p dist/linux/amd64 dist/linux/arm64
          # build for amd64
          env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -X main.version=${{ steps.tag.outputs.TAG }}" -o dist/linux/amd64/headmail ./cmd/server
          # build for arm64
          env GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -trimpath -ldflags="-s -w -X main.version=${{ steps.tag.outputs.TAG }}" -o dist/linux/arm64/headmail ./cmd/server
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist

  docker-push:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch Docker image (uses built binaries)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dist.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/headmail:${{ needs.build.outputs.TAG }}
            ghcr.io/${{ github.repository_owner }}/headmail:latest
          build-args: |
            VERSION=${{ needs.build.outputs.TAG }}

      - name: Confirm pushed image
        run: |
          echo "Pushed: ghcr.io/${GITHUB_REPOSITORY_OWNER}/headmail:${{ needs.build.outputs.TAG }} and :latest"
