name: Test

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.25
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Test
        run: |
          go test ./...

      - name: Build
        run: |
          go build -o headmail ./cmd/server/